configfile: "config.yaml"

rule all:
	input:
		expand("{outdir}/ART_reads/illumina_sim1.fq", outdir=config["sim_outdir"]),
		expand("{outdir}/ART_reads/illumina_sim2.fq", outdir=config["sim_outdir"])

rule simulate_nanopore_reads:
	params:
		config_dir=config["config_dir"],
		coverage=config["coverage"],
		error_profile=config["error_profile"],
		outdir=config["sim_outdir"],
		prefix=config["reads_prefix"],
		reference_genomes=config["reference_genomes"]
	output:
		expand("{outdir}/nanopore_reads/{reads_prefix}_sample0_aligned_reads.fastq", outdir=config["sim_outdir"], reads_prefix=config["reads_prefix"])
	conda:
		"nanosim_env"
	shell:
		"""
		source ~/anaconda3/etc/profile.d/conda.sh
		conda activate nanosim_env
		mkdir {params.outdir}/nanopore_reads || true
		
		python ../tools/simulate_nano.py --inputdir {params.reference_genomes} --coverage {params.coverage} --configdir {params.outdir}/nano_config --profile {params.error_profile} --outdir {params.outdir}/nanopore_reads/{params.prefix}
		"""

rule convert_fastq_to_fasta:
	input:
		expand("{outdir}/nanopore_reads/{reads_prefix}_sample0_aligned_reads.fastq", outdir=config["sim_outdir"], reads_prefix=config["reads_prefix"])
	output:
		expand("{outdir}/nanopore_reads/{reads_prefix}_sample0_aligned_reads.fasta", outdir=config["sim_outdir"], reads_prefix=config["reads_prefix"])
	shell:
		"sed -n \'1~4s/^@/>/p;2~4p\' \"{input}\" > \"{output}\""

rule art_illumina_sim:
	input:
		expand("{outdir}/nanopore_reads/{reads_prefix}_sample0_aligned_reads.fasta", outdir=config["sim_outdir"], reads_prefix=config["reads_prefix"])
	params:
		illumina_sim_dir=expand("{outdir}/ART_reads", outdir=config["sim_outdir"])
	output:
		expand("{outdir}/ART_reads/illumina_sim1.fq", outdir=config["sim_outdir"]),
		expand("{outdir}/ART_reads/illumina_sim2.fq", outdir=config["sim_outdir"])
	conda:
		"ART_env"
	shell:
		"""	
		source ~/anaconda3/etc/profile.d/conda.sh
		conda activate ART_env
		mkdir {params.illumina_sim_dir} || true
		art_illumina -p -sam -i {input} -o {params.illumina_sim_dir}/illumina_sim -l 50 -f 20 -m 200 -s 10
		"""
