#config_dir: "../nano_config/"
reads_prefix: "mgERR"
#coverage: 1
#reference_genomes: "/athena/ihlab/store/miw4007/simulation_test/input_seq/cleaned_seqs/2Spec"
#error_profile: "/athena/ihlab/store/miw4007/simulation_test/err_profs/metagenome_ERR3152364_Even/metagenome_ERR3152364_Even"
nanopore_reads: "nanopore_reads"
autobin_dir: "/athena/ihlab/scratch/miw4007/simulation_test/tools/snakemake_read_simulation/10S1C_autobin_output_3"
tax_database: "/athena/masonlab/scratch/databases/metagenomics/CAT_prepare_20210107/2021-01-07_taxonomy"
CAT_database: "/athena/masonlab/scratch/databases/metagenomics/CAT_prepare_20210107/2021-01-07_CAT_database"
refseq_genome: "/athena/ihlab/scratch/miw4007/simulation_test/refseq_genomic_combined.fna.gz"
#mm2_alignment_prefix: "/athena/ihlab/scratch/miw4007/mm2_mapping"
mm2_alignment_prefix: "mm2_mapping"
ncbi_tax_nodes: "/athena/masonlab/scratch/databases/metagenomics/ncbi_taxonomy_20220426/nodes.dmp"
tax_level: "species"
