configfile: "config.yaml"

rule all:
	input:
		#config["autobin_dir"] + "/flye_assembly/quast_results/report.html"
		#config["autobin_dir"] + "/CATBAT/CATBAT_bins/bin.0.fa"
		#config["autobin_dir"] + "/minimap2/flye_assembly/bin0/assembly_graph.gfa",
		#config["autobin_dir"] + "/CATBAT/flye_assembly/bin0/assembly_graph.gfa"
		config["autobin_dir"] + "/CATBAT/flye_assembly/bin0/quast_results/report.html"

rule mm2_map_to_bin:
	input:
		config["autobin_dir"] + "/AMBER_results/mm2_mapping.tsv"
	output:
		config["autobin_dir"] + "/minimap2/mm2_bins/bin.0.fa"
	params:
		autobin_dir=config["autobin_dir"],
		reads_prefix=config["reads_prefix"],
		nanopore_reads=config["nanopore_reads"]
	shell:
		"""
		source ~/anaconda3/etc/profile.d/conda.sh
		mkdir {params.autobin_dir}/minimap2/mm2_bins/ || true

		python ../tools/mm2_mapping_to_bins.py {params.autobin_dir}/AMBER_results/mm2_mapping.tsv {params.autobin_dir}/{params.nanopore_reads}/{params.reads_prefix}_sample0_aligned_reads.fasta {params.autobin_dir}/minimap2/mm2_bins/
		"""

rule CATBAT_map_to_bin:
	input:
		config["autobin_dir"] + "/AMBER_results/CATBAT_bins.tsv"
	output:
		config["autobin_dir"] + "/CATBAT/CATBAT_bins/bin.0.fa"
	params:
		autobin_dir=config["autobin_dir"],
		reads_prefix=config["reads_prefix"],
		nanopore_reads=config["nanopore_reads"]
	shell:
		"""
		mkdir {params.autobin_dir}/minimap2/mm2_bins/ || true

		python ../tools/CATBAT_mapping_to_bins.py {params.autobin_dir}/AMBER_results/CATBAT_bins.tsv {params.autobin_dir}/{params.nanopore_reads}/{params.reads_prefix}_sample0_aligned_reads.fasta {params.autobin_dir}/CATBAT/CATBAT_bins/
		"""


rule raw_flye_assembly:
	input:
		config["autobin_dir"] + "/" + config["nanopore_reads"] + "/" + config["reads_prefix"] + "_sample0_aligned_reads.fasta"
	output:
		config["autobin_dir"] + "/flye_assembly/assembly_graph.gfa"
	params:
		autobin_dir=config["autobin_dir"],
		reads_prefix=config["reads_prefix"],
		nanopore_reads=config["nanopore_reads"]
	conda:
		"flye_env"
	shell:
		"""
		source ~/anaconda3/etc/profile.d/conda.sh
		conda activate flye_env
		mkdir {params.nanopore_reads}/flye_assembly || true
		
		flye --nano-raw {params.autobin_dir}/{params.nanopore_reads}/{params.reads_prefix}_sample0_aligned_reads.fasta --out-dir {params.autobin_dir}/flye_assembly --threads 4
		"""


rule mm2_flye_assembly:
	input:
		config["autobin_dir"] + "/minimap2/mm2_bins/bin.0.fa"
	output:
		config["autobin_dir"] + "/minimap2/flye_assembly/bin0/assembly_graph.gfa"
	params:
		autobin_dir=config["autobin_dir"],
	conda:
		"flye_env"
	shell:
		"""
		source ~/anaconda3/etc/profile.d/conda.sh
		conda activate flye_env
		mkdir {params.autobin_dir}/minimap2/flye_assembly/ || true
		
		bash  ../tools/snakemake_assembly/meta_assembly.sh {params.autobin_dir}/minimap2/mm2_bins/ {params.autobin_dir}/minimap2/flye_assembly/
		"""


rule CATBAT_flye_assembly:
	input:
		config["autobin_dir"] + "/CATBAT/CATBAT_bins/bin.0.fa"
	output:
		config["autobin_dir"] + "/CATBAT/flye_assembly/bin0/assembly_graph.gfa"
	params:
		autobin_dir=config["autobin_dir"],
	conda:
		"flye_env"
	shell:
		"""
		source ~/anaconda3/etc/profile.d/conda.sh
		conda activate flye_env
		mkdir {params.autobin_dir}/CATBAT/flye_assembly/ || true
		
		bash ../tools/snakemake_assembly/meta_assembly.sh {params.autobin_dir}/CATBAT/CATBAT_bins/ {params.autobin_dir}/CATBAT/flye_assembly/
		"""

rule CATBAT_quast:
	input:
		config["autobin_dir"] + "/CATBAT/flye_assembly/bin0/assembly_graph.gfa"
	output:
		config["autobin_dir"] + "/CATBAT/flye_assembly/bin0/quast_results/report.html"
	params:
		autobin_dir=config["autobin_dir"],
	conda:
		"quast_env"
	shell:
		"""
		source ~/anaconda3/etc/profile.d/conda.sh
		conda activate quast_env
		#cd {params.autobin_dir}/CATBAT/flye_assembly
	
		bash ../tools/snakemake_assembly/meta_quast.sh {params.autobin_dir}/CATBAT/CATBAT_bins/ {params.autobin_dir}/CATBAT/flye_assembly/
		"""


rule mm2_quast:
	input:
		config["autobin_dir"] + "/minimap2/flye_assembly/bin0/assembly_graph.gfa"
	output:
		config["autobin_dir"] + "/minimap2/flye_assembly/bin0/quast_results/report.html"
	params:
		autobin_dir=config["autobin_dir"],
	conda:
		"quast_env"
	shell:
		"""
		source ~/anaconda3/etc/profile.d/conda.sh
		conda activate quast_env
		#cd {params.autobin_dir}/flye_assembly
	
		bash ../tools/snakemake_assembly/meta_quast.sh {params.autobin_dir}/minimap2/mm2_bins/ {params.autobin_dir}/minimap2/flye_assembly/
		"""


rule metaquast:
	input:
		config["autobin_dir"] + "/flye_assembly/assembly_graph.gfa"
	output:
		config["autobin_dir"] + "/flye_assembly/quast_results/report.html"
	params:
		autobin_dir=config["autobin_dir"]
	conda:
		"quast_env"
	shell:
		"""
		source ~/anaconda3/etc/profile.d/conda.sh
		conda activate quast_env
		cd {params.autobin_dir}/flye_assembly
		quast assembly.fasta -o quast_results/
		"""

