reads_prefix: "mgERR"
nanopore_reads: "nanopore_reads"
autobin_dir: ""
tax_database: "../databases/CAT_prepare_20210107/2021-01-07_taxonomy"
CAT_database: "../databases/CAT_prepare_20210107/2021-01-07_CAT_database"
refseq_genome: "../databases/refseq_genomic_combined.fna.gz"
mm2_alignment_prefix: "mm2_mapping"
ncbi_tax_nodes: "../databases/nodes.dmp"
tax_level: "species"
