reads_prefix: "mgERR"
nanopore_reads: "nanopore_reads"
autobin_dir: "/athena/ihlab/scratch/miw4007/NanoBinningSummer2022/new_10S10C_autobin_output_1"
tax_database: "/athena/masonlab/scratch/databases/metagenomics/CAT_prepare_20210107/2021-01-07_taxonomy"
CAT_database: "/athena/masonlab/scratch/databases/metagenomics/CAT_prepare_20210107/2021-01-07_CAT_database"
refseq_genome: "/athena/ihlab/scratch/miw4007/NanoBinningSummer2022/ref.fna.gz"
mm2_alignment_prefix: "mm2_mapping"
ncbi_tax_nodes: "/athena/masonlab/scratch/databases/metagenomics/NCBI_Taxonomy_20220426/nodes.dmp"
tax_level: "species"
